version: '2.4'

services:
  express:
    build:
      context: ./express
      # dockerfile: ./Dockerfile
    image: "express-tools"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
  playground:
    build:
      context: ./playground
      # dockerfile: ./Dockerfile
    image: "reacts"
    ports:
      - "3000:3000"
  postgres:
      user: postgres
      image: postgres:11.2-alpine
      restart: always
      healthcheck:
        test: pg_isready -h 127.0.0.1
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: playGround
        POSTGRES_PASSWORD: '5421'
    # links:
    #   - "backend:be"